"""Subclass of KeygenAct, which is generated by wxFormBuilder."""

import wx
import KeyGen
import keygen


# Implementing KeygenAct
class ActivatorKeygenAct(KeyGen.KeygenAct):

	def __init__(self, parent):
		KeyGen.KeygenAct.__init__(self, parent)

	# Handlers for KeygenAct events.
	def m_button1OnButtonClick(self, event):
		# TODO: Implement m_button1OnButtonClick
		print ("cancel")
		self.Close()
		pass

	def m_button2OnButtonClick(self, event):
		# TODO: Implement m_button2OnButtonClick
		print ("generate")
		if self.m_textCtrl1.GetValue() != "":
			print ("okay")
			self.lisensi = keygen.Lisensi(self.m_textCtrl1.GetValue())
			print (self.lisensi.hasil())
			# self.key = keygen.Key("3434-6346-6436-4334")
			self.key = keygen.Key('')		
			print (self.key)
			self.m_staticText4.SetLabel("tes")
		pass


if __name__ == '__main__':
	root = wx.App()
	run = ActivatorKeygenAct(None)
	run.Show()
	root.MainLoop()
	pass
