"""Subclass of FrameActivator, which is generated by wxFormBuilder."""

import wx
import activator
import aktivasi_keygen
import properties_aktiv
global lisensi


# Implementing FrameActivator
class ActivatorFrameActivator(activator.FrameActivator):

	def __init__(self, parent):
		activator.FrameActivator.__init__(self, parent)
		self.properties = properties_aktiv.PropertiesActiv(self)

	# Handlers for FrameActivator events.
	def m_button1OnButtonClick(self, event):
		# TODO: Implement m_button1OnButtonClick
		self.Close()
		pass

	def m_button2OnButtonClick(self, event):
		# TODO: Implement m_button2OnButtonClick
		lisensi = self.m_textCtrl1.GetValue()
		print (lisensi)
		self.a = aktivasi_keygen.AkLisen(self)
		print (self.a)

		print ("okay")
		pass


if __name__ == '__main__':
	root = wx.App()
	run = ActivatorFrameActivator(None)
	run.Show()
	root.MainLoop()
	pass
