"""Subclass of FrameWarningKey, which is generated by wxFormBuilder."""

import wx
import views.FrameKey as FrameKey
import random
import pathlib
from models.keygenapps.keygen import Key
from views.tempelfile import TempelFile
# Implementing FrameWarningKey


class authenticationFrameWarningKey(FrameKey.FrameWarningKey):


	def __init__(self, parent):
		FrameKey.FrameWarningKey.__init__(self, parent)
		self.SetSize((450,300))
		self.m_staticText6.SetLabel("")
		
		self.nilai = random.randint(1700, 1900)
		self.acak = random.randint(10000,99999)

		self.lisennombor =  str(self.nilai * 4) + str(self.acak)
		n = int(self.lisennombor)
	
		self.lastdigit = int(repr(n)[0:4])
		print (self.lastdigit)
		
		self.m_staticText144.SetLabel(str(self.lisennombor))

		# Handlers for FrameWarningKey events
		self.pathimage = pathlib.Path.cwd() / "resources/images/symbol/checked.png"
		self.image1 = wx.Image(str(self.pathimage))
		self.re_image1 = self.image1.Rescale(50, 50, quality=wx.IMAGE_QUALITY_NORMAL)
		print (self.pathimage)

		pass

	def m_textCtrl49OnText(self, event):
		# TODO: Implement m_textCtrl49OnText

		pass

	def m_button38OnButtonClick(self, event):
		# TODO: Implement m_button38OnButtonClick

		print ("batal")
		self.Close()
		pass

	def m_button39OnButtonClick(self, event):
		# TODO: Implement m_button39OnButtonClick

		self.keynumber = self.m_textCtrl49.GetValue()
		print (self.keynumber)
		lisensi = round(self.lastdigit/4)
		print (lisensi)
		self.gen = Key(self.keynumber)
		print ("aneh")
		print (self.gen.verify(lisensi))
		
		self.verify = self.gen.verify(lisensi)
		print (self.verify)
		self.yes = TempelFile(self.verify)
		self.yes.compilefile()
		if self.verify == True :
			self.m_staticText6.SetLabel("tervalidasi")
		elif self.verify == False :
			self.m_staticText6.SetLabel("Tidak Valid")
		else : 
			print ("gagal")

			
		# self.m_staticText6.SetLabel("Tidak Valid")
		pass
		
		if self.m_staticText6.GetLabel()== "tervalidasi":
			self.Close()
			print ("Berhasil")
			
		pass

	def m_button40OnButtonClick(self, event):
		print ("tutup")
		self.Close()

		
		pass

root = wx.App()
RunApp = authenticationFrameWarningKey(None)
RunApp.Show()
root.MainLoop()

