"""Subclass of VersiIST, which is generated by wxForopemBuilder."""

import views.istcore as istcore 
from views.properties_tampilan_versi import PropertiesTampilanVersi

# Implementing VersiIST
class ISTVersiIST( istcore.VersiIST ):
	def __init__( self, parent ):
		istcore.VersiIST.__init__( self, parent )
		self.__properties()
		
	def __properties(self):
		self.logo_properties2 = PropertiesTampilanVersi(self)

	def m_buttonVersiISTLanjutOnButtonClick(self, event):
		if self.m_radioBoxVersiIST.GetSelection() == 0 :
			# print ("Masuk Versi Seleksi")
			pass

		elif self.m_radioBoxVersiIST.GetSelection()== 1 :
			# print ("Masuk Versi Binakarir")
			pass
	
	def m_buttonTutupVersiISTOnButtonClick(self, event):
		self.Close()
		