"""Subclass of ISTUtama, which is generated by wxFormBuilder."""
import wx
from controllers.properties_ist import ISTInheritedProperties ,PropertiesInput
from controllers.properties_tampilan import PropertiesTampilan, AddTextCtrlProperties
from views.istcore import GridViewInputManual
# Implementing ISTUtama

class GridViewInherited(GridViewInputManual):

    def __init__(self,parent,*args,**kwds):
        super().__init__(parent,*args,**kwds)
        self.parent = parent
        self.parent.m_grid2 = self.m_grid2
        # import pdb
        # pdb.set_trace()
        self.parent.m_grid2.SetColLabelValue(0, "")
        self.parent.m_grid2.SetColLabelValue(1, "SE")
        self.parent.m_grid2.SetColLabelValue(2, "")
        self.parent.m_grid2.SetColLabelValue(3, "WA")
        self.parent.m_grid2.SetColLabelValue(4, "")
        self.parent.m_grid2.SetColLabelValue(5, "AN")
        self.parent.m_grid2.SetColLabelValue(6, "")
        self.parent.m_grid2.SetColLabelValue(7, "GE")
        self.parent.m_grid2.SetColLabelValue(8, "")
        self.parent.m_grid2.SetColLabelValue(9, "RA")
        self.parent.m_grid2.SetColLabelValue(10, "")
        self.parent.m_grid2.SetColLabelValue(11, "ZR")
        self.parent.m_grid2.SetColLabelValue(12, "")
        self.parent.m_grid2.SetColLabelValue(13, "FA")
        self.parent.m_grid2.SetColLabelValue(14, "")
        self.parent.m_grid2.SetColLabelValue(15, "WU")
        self.parent.m_grid2.SetColLabelValue(16, "")
        self.parent.m_grid2.SetColLabelValue(17, "ME")
        self.parent.m_grid2.SetColLabelValue(18, "")

        for l in range(0, 18):
            if not(l % 2):
                for i in range(0, 20):
                    stringval = i + 1

                    if l == 6 and i >= 16 :
                        self.parent.m_grid2.SetCellValue(i, l, "")
                        self.parent.m_grid2.SetCellBackgroundColour(i, l, "grey")
                        self.parent.m_grid2.SetReadOnly(i, l)

                    else :
                        # self.parent.m_grid2.SetCellBackgroundColour(i, l, "")
                        self.parent.m_grid2.SetCellValue(i, l, str(stringval))
                        # font = wx.Font(30,wx.DEFAULT ,wx.NORMAL, wx.NORMAL,0,"Tw Cent MT")
                        # self.parent.m_grid2.SetFont(font)
                        self.parent.m_grid2.SetCellAlignment(i, l, wx.ALIGN_CENTRE, wx.ALIGN_CENTRE)
                        self.parent.m_grid2.SetReadOnly(i, l)

            elif l == 7 and i >= 16 :
                for i in range(1, 20):
                    stringval = i + 1

                    if l == 7 and i >= 16 :
                        self.parent.m_grid2.SetCellValue(i, l, "")
                        self.parent.m_grid2.SetCellBackgroundColour(i, l, "grey")
                        self.parent.m_grid2.SetReadOnly(i, l)

                    else :
                        self.parent.m_grid2.SetCellValue(i, l, "")
                        self.parent.m_grid2.SetCellAlignment(i, l, wx.ALIGN_CENTRE, wx.ALIGN_CENTRE)
                        # self.parent.m_grid2.SetReadOnly(i, l)
    def getdata(self):
        self.data = []

        for i in range (0,20):
            self.datapertama = []
            for l in range(0,18):
                if l % 2:
                    self.a = self.parent.m_grid2.GetCellValue(i, l)
                    self.datapertama.append(self.a)

            self.data.append(self.datapertama)

        return self.data

    def gridOkOnButtonClick(self,event):

        self.Close()




class ISTISTUtama(ISTInheritedProperties):

    def __init__(self, parent , *args, **kwds):
        super().__init__(parent, *args, **kwds)
        self.m_simplebook1.SetSelection(0)
        self.properties_tamp = PropertiesTampilan(self)
        self.properties_tamp.logo_show()
        self.properties_tamp.tabel_show()
        self.data_peserta = PropertiesInput(self)
        # print (self.properties_listcontrol.list_an)
        # for listtext in self.properties_listcontrol.list_an :
        #   print (listtext.SetValue("A"))
        self.m_selanjutnya.Disable()
        self.Maximize()
        pass
    
    def requiredclick(self,event) :

        if self.m_textCtrl_no_tes.GetValue()== "":
            self.m_selanjutnya.Disable()
        else:
            self.m_selanjutnya.Enable()

        pass



    # def m_button_hapus_onclick( self, event ):
    #   print ("hapus dari database")
    #   event.Skip()

    # def m_button_filter_onclick( self, event ):
    #   print ("you have click 'Filter'")
    #   self.openfilter = BukaFilter(self)
    #   self.openfilter.Show()
    #   event.Skip()

    # def m_button_lihat_dari_database_onclick( self, event ):
    #   print ("lihat dari database")
    #   event.Skip()

    # def m_button_reset_onclick( self, event ):
    #   print ("reset dari halaman terakhir")
    #   event.Skip()
    
    # def m_buttonInput_JawabanOnButtonClick(self, event):
    #     self.m_notebook1.SetSelection(1)
    #     print ("Input Jawaban is over here")
    
        #   def m_buttonInput_TotalOnButtonClick(self, event):
        #       self.m_notebook1.SetSelection(2)
        #       print ("Input Total is over here")
        
    # def m_textCtrl47OnText(self, event):
    #     print ("respon on 'input total'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolse()
        
    #     pass
    
    # def m_textCtrl6OnText(self, event):
    #     print ("respon on 'input jawaban'")

    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolsetotal()
    #     self.se = ListControlProperties(self)
    #     print (self.se.totalse())
    #     pass
    
    # def m_textCtrl48OnText(self, event):
    #     print ("respon on 'input total'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolwa()
    #     pass
    
    # def m_textCtrl7OnText(self, event):
    #     print ("respon on 'input jawaban'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolwatotal()
    #     pass
    
    # def m_textCtrl481OnText(self, event):
    #     print ("respon on 'input total'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolan()
    #     pass
    
    # def m_textCtrl71OnText(self, event):
    #     print ("respon on 'input jawaban'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolantotal()
    #     pass

    # def m_textCtrl181OnText(self, event):
    #     print ("respon on 'input total'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolra()
    #     pass
    
    # def m_textCtrl30OnText(self, event):
    #     print ("respon on 'input jawaban'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolratotal()
    #     pass

    # def m_textCtrl196OnText(self, event):
    #     print ("respon on 'input total'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolzr()
    #     pass
    
    # def m_textCtrl10OnText(self, event):
    #     print ("respon on 'input jawaban'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolzrtotal()
    #     pass

    # def m_textCtrl484OnText(self, event):
    #     print ("respon on 'input total'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolfa()
    #     pass
    
    # def m_textCtrl74OnText(self, event):
    #     print ("respon on 'input jawaban'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolfatotal()
    #     pass

    # def m_textCtrl75OnText(self, event):
    #     print ("respon on 'input jawaban'")

    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolwutotal()
    #     pass
    
    # def m_textCtrl485OnText(self, event):
    #     print ("respon on 'input jawaban a'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolwu()
    #     pass

    # def m_textCtrl76OnText(self, event):
    #     print ("respon on 'input jawaban'")

    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolmetotal()
    #     pass
    
    # def m_textCtrl486OnText(self, event):
    #     print ("respon on 'input jawaban a'")
    #     self.control = AddTextCtrlProperties(self)
    #     self.control.enabledisablecontrolme()
    #     pass
    
    # def m_button6OnButtonClick(self, event):
    #     # Klik for calculating \
    #     print ("over here")
    #     self.run_calculate = ListControlProperties(self)
        
    #     pass
    # 